from typing import Any

# The settings a Webview is built from are declared once, in `dry.interface`.
# This is the internal call that carries them across to Rust, and the mapping
# it takes is not part of the public surface.
def run(settings: dict[str, Any]) -> None: ...

# The Event half of the Bridge, Python to frontend. The value crosses under the
# Bridge contract, `default=` hook included, and nothing comes back.
def emit_event(name: str, value: Any) -> None: ...

# The raw script-evaluation escape hatch, in place of a Python-to-frontend Call
# with a return value. Returns nothing: see ADR-0001.
def eval_js(script: str) -> None: ...

# Runtime window control. Each of these posts one change to the thread that
# owns the window and returns; the Event that says it happened comes from the
# window state diff, so a change made here and a change the user made arrive
# the same way. Sizes and positions are logical pixels. Every one of them
# raises WebviewError when no window is running.
def set_window_title(title: str) -> None: ...
def set_window_size(size: tuple[int, int]) -> None: ...
def set_window_min_size(min_size: tuple[int, int]) -> None: ...
def set_window_decorations(decorations: bool) -> None: ...
def set_window_icon(icon_path: str | None) -> None: ...
def set_window_position(position: tuple[int, int]) -> None: ...
def set_window_visible(visible: bool) -> None: ...
def set_window_maximized(maximized: bool) -> None: ...
def set_window_minimized(minimized: bool) -> None: ...
def set_window_fullscreen(fullscreen: bool) -> None: ...

# What the window is doing, from the last reading the event loop took. The
# mapping is the same shape the frontend's `window.dry.state()` resolves with;
# `dry.interface` is where it becomes the public WindowState.
def window_state() -> dict[str, Any]: ...

class DryError(Exception): ...
class WebviewError(DryError): ...
class BridgeError(DryError): ...
class PanicError(DryError): ...
