from typing import Any

# The settings a Webview is built from are declared once, in `dry.interface`.
# This is the internal call that carries them across to Rust, and the mapping
# it takes is not part of the public surface.
def run(settings: dict[str, Any]) -> None: ...

# The Event half of the Bridge, Python to frontend. The value crosses under the
# Bridge contract, `default=` hook included, and nothing comes back.
def emit_event(name: str, value: Any) -> None: ...

# The raw script-evaluation escape hatch, in place of a Python-to-frontend Call
# with a return value. Returns nothing: see ADR-0001.
def eval_js(script: str) -> None: ...

class DryError(Exception): ...
class WebviewError(DryError): ...
class BridgeError(DryError): ...
class PanicError(DryError): ...
