from typing import Any

# The settings a Webview is built from are declared once, in `dry.interface`.
# This is the internal call that carries them across to Rust, and the mapping
# it takes is not part of the public surface.
def run(settings: dict[str, Any]) -> None: ...
def send_event(message: str) -> None: ...

class DryError(Exception): ...
class WebviewError(DryError): ...
class BridgeError(DryError): ...
class PanicError(DryError): ...
